---
package_list:
  - libselinux-python
  - vim
  - git
  - tmux
  - screen
  - chrony

rhn_default_repo_list:
  - rhel-7-server-rpms
  - rhel-7-server-supplementary-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-extras-rpms

nameserver: "192.168.4.10"

