---
- name: Install packages - dnf and update OS
  dnf: 
    name: "{{ item }}"
    state: present
  with_items: "{{ package_list }}"
  when: ansible_pkg_mgr == "dnf"

- name: Install packages - yum and update OS
  yum: 
    name: "{{ item }}"
    state: present
  with_items: "{{ package_list }}"
  when: ansible_pkg_mgr == "yum"

